apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
  - name: data-processor
    image: data-processor
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In 
              values:
              - Large
              - Medium

