apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
# Config Map
  envFrom:
    secretRef:
      name: app-config # This is the 'name' label on the config-map.yaml file

