apiVersion: v1 
kind: Config 

# Can specify the default cotext (if you have more than one):
current-context: {USERNAME}@{CLUSTER}

clusters:
- name: {CLUSTER_NAME}
  cluster:
    certificate-authority: {CA_CERT_PATH}
    server: {CLUSTER_SERVER}

context: 
- name: {USERNAME}@{CLUSTER}
  context: 
    cluster: {CLUSTER}
    user: {USERNAME}
    namespace: {NAMESPACE} # Optional


users: 
- name: {USERNAME}
  user: 
    client-certificate: {USER_CERT_PATH}
    client-key: {USER_KEY_PATH}

