apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx-app
    type: front-end
spec:
  selector:
    matchLabels:
      app: nginx-app
      type: front-end
  replicas: 6
  template: 
    metadata: 
      name: nginx
      labels:
        app: nginx-app
        type: front-end
    spec: 
      containers:
        - name: nginx
          image: nginx